//alloys go brrr - ima go insane :)

ServerEvents.recipes(event => {
    event.recipes.gtceu.alloy_smelter('kubejs:dark_steel_ingot')
        .itemInputs('#forge:ingots/steel', '#forge:obsidian')
        .itemOutputs('gtceu:dark_steel_ingot')
        .duration(240)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:dark_steel_ingot_from_obsidian_dust')
        .itemInputs('#forge:ingots/steel', '#forge:dusts/obsidian')
        .itemOutputs('gtceu:dark_steel_ingot')
        .duration(240)
        .EUt(16)

    event.recipes.gtceu.alloy_smelter('kubejs:conductive_alloy_ingot')
        .itemInputs('#forge:ingots/iron', '#forge:dusts/redstone')
        .itemOutputs('gtceu:conductive_alloy_ingot')
        .duration(150)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:conductive_alloy_ingot_from_iron_dust')
        .itemInputs('#forge:dusts/iron', '#forge:dusts/redstone')
        .itemOutputs('gtceu:conductive_alloy_ingot')
        .duration(150)
        .EUt(16)

    event.recipes.gtceu.alloy_smelter('kubejs:pulsating_alloy_ingot')
        .itemInputs('#forge:ingots/iron', 'kubejs:pulsating_dust')
        .itemOutputs('gtceu:pulsating_alloy_ingot')
        .duration(150)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:pulsating_alloy_ingot_from_iron_dust')
        .itemInputs('#forge:dusts/iron', 'kubejs:pulsating_dust')
        .itemOutputs('gtceu:pulsating_alloy_ingot')
        .duration(150)
        .EUt(16)

    event.recipes.gtceu.alloy_smelter('kubejs:electrical_steel_ingot')
        .itemInputs('#forge:ingots/steel', '#forge:dusts/silicon')
        .itemOutputs('gtceu:electrical_steel_ingot')
        .duration(120)
        .EUt(16)

    event.recipes.gtceu.alloy_smelter('kubejs:end_steel_ingot')
        .itemInputs('#forge:ingots/dark_steel', 'minecraft:end_stone')
        .itemOutputs('gtceu:end_steel_ingot')
        .duration(300)
        .EUt(120)
    event.recipes.gtceu.alloy_smelter('kubejs:end_steel_ingot_from_endstone_dust')
        .itemInputs('#forge:ingots/dark_steel', '#forge:dusts/endstone')
        .itemOutputs('gtceu:end_steel_ingot')
        .duration(300)
        .EUt(120)

    // event.recipes.gtceu.alloy_smelter('kubejs:stellar_alloy_ingot')
    //   .itemInputs('#forge:ingots/end_steel', '8x enderio:infinity_dust')
    //   .itemOutputs('gtceu:stellar_alloy_ingot')
    //   .duration(200)
    //   .EUt(2000)

    event.recipes.gtceu.alloy_smelter('kubejs:ferroboron_ingot')
        .itemInputs('#forge:ingots/steel', '#forge:dusts/boron')
        .itemOutputs('2x nuclearcraft:ferroboron_ingot')
        .duration(300)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:tough_alloy_ingot')
        .itemInputs('#forge:ingots/ferroboron', '#forge:dusts/lithium')
        .itemOutputs('2x nuclearcraft:tough_alloy_ingot')
        .duration(300)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:hard_carbon_ingot')
        .itemInputs('2x #forge:ingots/steel', '#forge:gems/diamond')
        .itemOutputs('2x nuclearcraft:hard_carbon_ingot')
        .duration(300)
        .EUt(16)
    event.recipes.gtceu.alloy_smelter('kubejs:sunnarium_dust')
        .itemInputs('kubejs:stabilized_plutonium', 'kubejs:stabilized_curium')
        .itemOutputs('gtceu:sunnarium_dust')
        .duration(2000)
        .EUt(400)
    event.recipes.gtceu.alloy_smelter('kubejs:fission_reactor_glass')
        .itemInputs('nuclearcraft:fission_reactor_casing', '#forge:glass/colorless')
        .itemOutputs('nuclearcraft:fission_reactor_glass')
        .duration(50)
        .EUt(16)

    event.remove({ id: "minecraft:nuclearcraft_ferroboron_plate" }) // minecraft??
    event.remove({ id: "minecraft:nuclearcraft_ferroboron_dust" })
    event.remove([{ id: "nuclearcraft:blast_ferroboron_dust" }, { id: "nuclearcraft:fission_reactor_glass" }])
})


ServerEvents.recipes(event => {
    //Different Steel Recipe
    event.remove({ id: "gtceu:centrifuge/decomposition_centrifuging__black_steel" })
    event.remove({ id: "gtceu:mixer/black_steel" })
    event.recipes.gtceu.mixer("kubejs:conductive_alloy_dust") // on gtceu normal, this can be handcrafted
        .itemInputs('#forge:dusts/iron', '#forge:dusts/redstone')
        .itemOutputs('gtceu:conductive_alloy_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.mixer("kubejs:black_steel_dust")
        .itemInputs('3x gtceu:steel_dust', '2x gtceu:black_bronze_dust', '2x gtceu:void_gem', '2x gtceu:coal_perfect')
        .itemOutputs('9x gtceu:black_steel_dust')
        .duration(200)
        .EUt(15)

    event.recipes.gtceu.mixer("kubejs:vibrant_alloy_dust")
        .itemInputs('gtceu:energetic_alloy_dust', 'gtceu:ender_pearl_dust')
        .itemOutputs('gtceu:vibrant_alloy_dust')
        .duration(200)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:energetic_alloy_dust")
        .itemInputs('2x gtceu:gold_dust', '#forge:dusts/redstone', 'minecraft:glowstone_dust')
        .itemOutputs('2x gtceu:energetic_alloy_dust')
        .duration(200)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:glowstone_dust")
        .itemInputs('gtceu:tricalcium_phosphate_dust', 'gtceu:gold_dust')
        .itemOutputs('2x minecraft:glowstone_dust')
        .duration(80)
        .EUt(15)

    event.recipes.gtceu.mixer("kubejs:mana_infused_dust")
        .itemInputs('kubejs:primal_mana', 'gtceu:titanium_dust')
        .itemOutputs('gtceu:mana_infused_metal_dust')
        .duration(200)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:lumium_dust")
        .itemInputs('4x gtceu:tin_alloy_dust', '2x gtceu:sterling_silver_dust', '2x extendedcrafting:luminessence', 'kubejs:energized_clathrate')
        .itemOutputs('4x gtceu:lumium_dust')
        .inputFluids(Fluid.of('kubejs:molten_primal_mana', 250))
        .duration(200)
        .EUt(1920)

    event.recipes.gtceu.mixer("kubejs:signalum_dust")
        .itemInputs('4x gtceu:annealed_copper_dust', '2x gtceu:ardite_dust', '2x gtceu:red_alloy_dust', 'kubejs:destabilized_clathrate')
        .itemOutputs('4x gtceu:signalum_dust')
        .inputFluids(Fluid.of('kubejs:molten_primal_mana', 250))
        .duration(200)
        .EUt(1920)

    event.recipes.gtceu.mixer("kubejs:rhodium_plated_palladium_dust")
        .itemInputs('3x gtceu:palladium_dust', 'gtceu:rhodium_dust', '2x gtceu:lumium_dust')
        .itemOutputs('6x gtceu:rhodium_plated_palladium_dust')
        .duration(400)
        .EUt(7680)
        .circuit(1)

    event.recipes.gtceu.mixer("kubejs:enderium_dust")
        .itemInputs('4x gtceu:lead_dust', '2x gtceu:platinum_dust', 'gtceu:blue_steel_dust', 'gtceu:osmium_dust', 'kubejs:resonant_clathrate')
        .itemOutputs('4x gtceu:enderium_dust')
        .inputFluids(Fluid.of('kubejs:molten_primal_mana', 1000))
        .duration(300)
        .EUt(1920)

    event.recipes.gtceu.mixer("kubejs:ardite_dust")
        .itemInputs('3x gtceu:red_steel_dust', 'minecraft:blaze_powder')
        .itemOutputs('4x gtceu:ardite_dust')
        .duration(200)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:manyullyn_dust")
        .itemInputs('4x gtceu:ardite_dust', '4x gtceu:cobalt_dust', 'kubejs:primal_mana')
        .itemOutputs('4x gtceu:manyullyn_dust')
        .duration(400)
        .EUt(30)
})

ServerEvents.recipes(event => {
    event.recipes.gtceu.electric_blast_furnace("kubejs:mana_infused_metal")
        .itemInputs('gtceu:mana_infused_metal_dust')
        .itemOutputs('gtceu:mana_infused_metal_ingot')
        .inputFluids(Fluid.of('kubejs:molten_primal_mana', 250))
        .duration(400)
        .EUt(400)
        .blastFurnaceTemp(2141)
})

ServerEvents.recipes(event => {
    event.remove('gtceu:alloy_blast_smelter/red_alloy')
    event.recipes.gtceu.alloy_blast_smelter("red_alloy_fluid")
        .itemInputs('2x gtceu:copper_dust', '3x #forge:dusts/redstone')
        .outputFluids(Fluid.of('gtceu:red_alloy', 288))
        .duration(75)
        .EUt(16)
        .circuit(5)
        .blastFurnaceTemp(1400)
    event.recipes.gtceu.alloy_blast_smelter("kubejs:conductive_alloy_fluid")
        .itemInputs('#forge:dusts/iron', '#forge:dusts/redstone')
        .outputFluids(Fluid.of('gtceu:conductive_alloy', 144))
        .duration(225)
        .EUt(16)
        .circuit(2)
        .blastFurnaceTemp(1400)
    event.recipes.gtceu.alloy_blast_smelter("kubejs:energetic_alloy_fluid")
        .itemInputs('2x gtceu:gold_dust', '#forge:dusts/redstone', 'minecraft:glowstone_dust')
        .outputFluids(Fluid.of('gtceu:energetic_alloy', 576))
        .duration(1200)
        .EUt(120)
        .circuit(3)
        .blastFurnaceTemp(1250)

    event.recipes.gtceu.alloy_blast_smelter("kubejs:energetic_alloy_fluid_from_gold_dust")
        .itemInputs('2x gtceu:gold_dust', '#forge:dusts/redstone', 'minecraft:glowstone_dust')
        .inputFluids(Fluid.of('gtceu:nitrogen', 4000))
        .outputFluids(Fluid.of('gtceu:energetic_alloy', 576))
        .duration(600)
        .EUt(120)
        .circuit(13)
        .blastFurnaceTemp(1250)

    event.recipes.gtceu.alloy_blast_smelter("kubejs:vibrant_alloy_fluid")
        .itemInputs('gtceu:energetic_alloy_dust', 'gtceu:ender_pearl_dust')
        .outputFluids(Fluid.of('gtceu:vibrant_alloy', 288))
        .duration(600) // 30s
        .EUt(120)
        .circuit(2)
        .blastFurnaceTemp(1350)

    event.recipes.gtceu.alloy_blast_smelter("kubejs:vibrant_alloy_fluid_from_energetic_dust")
        .itemInputs('gtceu:energetic_alloy_dust', 'gtceu:ender_pearl_dust')
        .inputFluids(Fluid.of('gtceu:nitrogen', 2000))
        .outputFluids(Fluid.of('gtceu:vibrant_alloy', 288))
        .duration(402) // 20.1s
        .EUt(120)
        .circuit(12)
        .blastFurnaceTemp(1350)

	// soularium
    event.recipes.gtceu.alloy_blast_smelter('kubejs:solarium_fluid')
        .itemInputs('#forge:dusts/gold', 'soul_sand')
		.circuit(2)
        .outputFluids(Fluid.of('gtceu:soularium', 144))
        .duration(90) // 4.5s
        .EUt(16)
        .blastFurnaceTemp(1200)

	// nomi ceu 1.7 normal
	event.recipes.gtceu.electric_blast_furnace('kubejs:dark_soularium_ingot')
		.itemInputs('#forge:ingots/soularium', '#forge:ingots/dark_steel')
		.inputFluids(Fluid.of('gtceu:tritium', 1000))
		.itemOutputs('gtceu:dark_soularium_ingot')
		.duration(1200) // 60 sec
		.EUt(32000)
		.blastFurnaceTemp(8600)
})